### PR TITLE
Allow stopwatch to also count time down.

### PR DESCRIPTION
**Pull request by rushiagr**
Borrowed from mario's implementation at
http://www.seph.dk/blog/projects/javascript-stopwatch-class/comment-page-1/#comment-11145
in the comment on the blog-cum-documentation at
http://www.seph.dk/blog/projects/javascript-stopwatch-class/

### CODE REVIEW

**Comment by scarlac** [comment]
Hi @rushiagr 

Thank you for the submission.
Have you tested the feature with getElapsed, etc? It should make sense for all method calls.
- Seph

**Comment by rushiagr** [comment]
I tested getElapsed, and it is working fine. Not sure about the other
methods. Frankly I didnt paid much attention -- just pasted what mario
wrote in comments and found it working.

I have some more ideas in mind for the watch:
Add a loop: once a time is set via setElapsed, the counter, after reaching
0, starts over again from the time set by setElapsed.
String formatting: for example, only display minutes and seconds, and not
the hours, or showseconds upto a precision.

I cant guarantee i can soend time on them, but i can open them as issues if
you deem them as useful additions!

**Comment by rushiagr** [comment]
You want me to test other functions as well? I'll be happy to do that!

**Comment by scarlac** [comment]
@rushiagr Yeah, that'd be great! The reverse functionality may make some of the methods invalid, so I want to make sure it all makes sense - and works! :)

**Comment by rushiagr** [comment]
@scarlac sure, will do that soon. Thanks!

**Pull request merged**
